library("shiny")
library("shinydashboard")
library("ggplot2")
library("ggthemes")
library("DT")
library("plotly")
library("shinyjs")
library("bdvis")

shinyUI(
    hidden(
        div(id = "full_page",
            dashboardPage(
                dashboardHeader(title = "Visualizing Mammalia Data from USA using bdvis", titleWidth = "95%"),
                dashboardSidebar(
                    width = 300,
                    tags$img(src = "logo.jpg", height = 200, width = 300, align = "bottom"),
                    sidebarMenu(
                        menuItem(h4("Project Summary"), tabName = "summary", icon = icon(name = "industry")),
                        menuItem(h4("View Dataset"), tabName = "dataset", icon = icon("address-book-o")),
                        menuItem(h4("View Tempolar Graphs"), tabName = "tempolar", icon = icon("globe")),
                        menuItem(h4("View Chronohorogram"), tabName = "chronohorogram", icon = icon("rocket")),
                        menuItem(h4("View MapGrids"), tabName = "mapgrids", icon = icon("mortar-board")),
                        menuItem(h4("View Calendar HeatMap"), tabName = "heatmap", icon = icon("clipboard")),
                        menuItem(h4("About"), tabName = "about", icon = icon("clipboard"))
                    )
                ),
                
                dashboardBody(
                    tabItems(
                        tabItem(tabName = "summary",
                                tags$h2(tags$u("Hello and Welcome: ")),
                                h3("Welcome to the visualizations of the Mammalia Data acquired from GBIF in the United States of America."),
                                h3("You can view the top 10,000 results that I downloaded using the rgbif package."),
                                h3("Also, several different plots created using the bdviz package can be viewed too."),
                                h2(tags$u("Summary generated by the bdvis package: ")),
                                h3( "Total no of records = 10000"), 
                                h3("Temporal coverage..."),   
                                h3("Date range of the records from  2011-12-01  to  2021-02-11"),
                                h3("Taxonomic coverage..."),
                                h3("No of Families :  0"),
                                h3("No of Genus :  0"),
                                h3("No of Species :  216"),
                                h3("Spatial coverage ... "),
                                h3("Bounding box of records  19.181186 , -161.719712  -  64.556209 , -68.046399"),
                                h3("Degree celles covered :  34 "),
                                h3("% degree cells covered :  0.812425328554361 ")
                        ),
                        tabItem(tabName = "dataset", 
                                fluidRow(box(status = "primary", div(style = 'overflow-x: scroll', DTOutput('mammal_data_table')), width = 12))
                        ),
                        tabItem(tabName = "tempolar",
                                fluidRow(box(status = "primary", plotOutput("mammal_tempolar_daily"), width = 8),
                                         valueBoxOutput(outputId = "tempolar_daily")),
                                fluidRow(box(status = "primary", plotOutput("mammal_tempolar_weekly"), width = 8),
                                         valueBoxOutput(outputId = "tempolar_weekly")),
                                fluidRow(box(status = "primary", plotOutput("mammal_tempolar_monthly"), width = 8),
                                         valueBoxOutput(outputId = "tempolar_monthly"))
                        ),
                        tabItem(tabName = "chronohorogram",
                                fluidRow(box(status = "primary", plotOutput("mammal_chronohorogram"), width = 8),
                                         valueBoxOutput(outputId = "chronohorogram_params"))
                        ),
                        tabItem(tabName = "mapgrids",
                                fluidRow(box(status = "primary", plotlyOutput("map_record"), width = 8),
                                         valueBoxOutput(outputId = "record_param")),
                                fluidRow(box(status = "primary", plotlyOutput("map_presence"), width = 8),
                                         valueBoxOutput(outputId = "presence_param")),
                                fluidRow(box(status = "primary", plotlyOutput("map_complete"), width = 8),
                                         valueBoxOutput(outputId = "complete_param"))
                        ),
                        tabItem(tabName = "heatmap",
                                fluidRow(box(status = "primary", plotOutput("mammal_heatmap"), width = 8),
                                         valueBoxOutput(outputId = "heatmap_params"))
                        ),
                        tabItem(tabName = "about",
                                tags$div(
                                    tags$h2(tags$u("About the Developer: ")),
                                    h3("Ciao, I'm", tags$b("Rahul Saxena"), ", a final year Computer Science undergraduate at IIIT-Bhubaneswar, India. This Shiny app is my attempt at the test given at the Productionizing `bddashboard` wiki"),                                    h3("You can find me on ") ,
                                    h3(tags$a(href="https://github.com/hinduBale", "Github")),
                                    h3(tags$a(href="https://www.linkedin.com/in/saxena-rahul/", "LinkedIn")),
                                    h3(tags$a(href="https://twitter.com/hinduBale", "Twitter")),
                                    h3(tags$a(href="https://www.quora.com/profile/Rahul-Saxena-30", "Quora")),
                                    h3(tags$a(href="https://www.instagram.com/saxenism/", "Instagram")),
                                    h3("If you liked my work, consider following", tags$a(href = "https://github.com/hinduBale", "me on github."), ", or sending me some anime memes :P"),
                                    h3("Thanks for dropping by. Peace _/\\_")
                                )
                        )
                    )
                )
                
            )
        )
    )
)